### ISSUE TITLE
Window too big to fit in screen

### ISSUE THREAD

**Issue by XCraftMC23** [R2NorthstarTools/VTOL#62]
**Describe the bug**
The window for VTOL is too big to fully fit in the screen, so I am unable to access some buttons.
**To Reproduce**
1. Open the app
2. Try to resize the window
3. Be frustrated

**Expected behavior**
I should be able to resize the window to fit my screen

**Desktop (please complete the following information):**
 - OS: Win 11

**Comment by BigSpice** [comment]
What is your native resolution.

**Comment by XCraftMC23** [comment]
1920x1080. It's on a laptop, and it's scaled 150%. 150 is the only one I find usable.

**Comment by GitCat3** [comment]
I am having a similar issue, resolution is 1920x1080 at 100%, and part of the window is cut off, so some of the mods are not visible, as shown
![image](https://github.com/R2NorthstarTools/VTOL/assets/58991273/4a3acd1d-62ce-4893-a2b7-a663b3882197)

**Comment by ASpoonPlaysGames** [comment]
> ![image](https://user-images.githubusercontent.com/58991273/242995140-4a3acd1d-62ce-4893-a2b7-a663b3882197.png)

Looking at this image, you may need to update VTOL? I'm fairly certain you are a few patches behind at least @GitCat3

**Comment by BigSpice** [comment]
Please @GitCat3 , try minimizing that side tray first. And please explore the ui again.

**Comment by BigSpice** [comment]
@XCraftMC23 unusual but I will make changes to 3.0.1 to remain unchanged by magnification settings

**Comment by BigSpice** [comment]
Fixed and shipping a version in the next few days

**Comment by BigSpice** [comment]
apologies, have been on work trip. 
have you seen and tried the current ver?.

**Comment by juppytaar** [comment]
dont know if info is still needed but...yes, issue remains sadly unchanged.
1920*1080 and the same cut view like the guys before. no option to rescale or even resize window

**Comment by BigSpice** [comment]
fixed
pushing in new release friday

**Comment by BigSpice** [comment]
fixed 
![image](https://github.com/R2NorthstarTools/VTOL/assets/23240514/d6d8eaae-617a-4b9f-ac76-43127bf99976)
